/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ailatrieuphu;

import javax.swing.JFrame;

/**
 *
 * @author mnngu
 */
public class HowToPlay extends javax.swing.JFrame {

    /**
     * Creates new form HowToPlay
     */
    private int width = 1200;
    private int height = 660;
    public HowToPlay() {
        
        initComponents();
        setSize(width, height);
        setLocationRelativeTo(null);
        
        setTitle("Ai La Trieu Phu [Menu]");
        setResizable(false);
        setVisible(true);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        lbl50_50.setVisible(false);
        lblAudience.setVisible(false);
        lblChangQuestion.setVisible(false);
        lblChatHelp.setVisible(false);
        btnPrevious.setVisible(false);
        
    }
    public void resetLabel(){
        lblAudience.setVisible(false);
        lbl50_50.setVisible(false);
        lblChatHelp.setVisible(false);
        lblChangQuestion.setVisible(false);
        main_HowToPlay.setVisible(false);
        btnAudience.setVisible(true);
        btn50_50.setVisible(true);
        btnChangeQuestion.setVisible(true);
        btnChatHelp.setVisible(true);
        
        btn50_50.setLocation(660,150);
        btnChatHelp.setLocation(660,250);
        btnAudience.setLocation(660,340);
        btnChangeQuestion.setLocation(660,430);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPrevious = new javax.swing.JLabel();
        btnChatHelp = new javax.swing.JLabel();
        btnAudience = new javax.swing.JLabel();
        btn50_50 = new javax.swing.JLabel();
        backHomeBTN = new javax.swing.JLabel();
        btnChangeQuestion = new javax.swing.JLabel();
        main_HowToPlay = new javax.swing.JLabel();
        lbl50_50 = new javax.swing.JLabel();
        lblAudience = new javax.swing.JLabel();
        lblChangQuestion = new javax.swing.JLabel();
        lblChatHelp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backButtuon.png"))); // NOI18N
        btnPrevious.setToolTipText("");
        btnPrevious.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrevious.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPreviousMouseClicked(evt);
            }
        });
        btnPrevious.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPreviousKeyPressed(evt);
            }
        });
        getContentPane().add(btnPrevious);
        btnPrevious.setBounds(30, 550, 100, 70);

        btnChatHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chatHelp.png"))); // NOI18N
        btnChatHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChatHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChatHelpMouseClicked(evt);
            }
        });
        getContentPane().add(btnChatHelp);
        btnChatHelp.setBounds(660, 340, 140, 80);

        btnAudience.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ask_audience.png"))); // NOI18N
        btnAudience.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAudience.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAudienceMouseClicked(evt);
            }
        });
        getContentPane().add(btnAudience);
        btnAudience.setBounds(660, 250, 130, 80);

        btn50_50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/50_50.png"))); // NOI18N
        btn50_50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn50_50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn50_50MouseClicked(evt);
            }
        });
        getContentPane().add(btn50_50);
        btn50_50.setBounds(660, 150, 100, 90);

        backHomeBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homeButton.png"))); // NOI18N
        backHomeBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backHomeBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backHomeBTNMouseClicked(evt);
            }
        });
        getContentPane().add(backHomeBTN);
        backHomeBTN.setBounds(1070, 520, 80, 80);

        btnChangeQuestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/changeQuestion.png"))); // NOI18N
        btnChangeQuestion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChangeQuestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChangeQuestionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnChangeQuestionMouseEntered(evt);
            }
        });
        getContentPane().add(btnChangeQuestion);
        btnChangeQuestion.setBounds(660, 430, 110, 70);

        main_HowToPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/6.png"))); // NOI18N
        getContentPane().add(main_HowToPlay);
        main_HowToPlay.setBounds(0, 0, 1200, 600);

        lbl50_50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/7.png"))); // NOI18N
        getContentPane().add(lbl50_50);
        lbl50_50.setBounds(0, 0, 1200, 620);

        lblAudience.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/8.png"))); // NOI18N
        getContentPane().add(lblAudience);
        lblAudience.setBounds(0, 0, 1200, 620);

        lblChangQuestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/9.png"))); // NOI18N
        getContentPane().add(lblChangQuestion);
        lblChangQuestion.setBounds(0, 0, 1200, 620);

        lblChatHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/10.png"))); // NOI18N
        getContentPane().add(lblChatHelp);
        lblChatHelp.setBounds(-3, -4, 1200, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn50_50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn50_50MouseClicked
        // TODO add your handling code here:
        resetLabel();
        
        btnPrevious.setVisible(true);
        btnChatHelp.setLocation(btnChatHelp.getX(), btnChatHelp.getY()-80);
        btnAudience.setLocation(btnAudience.getX(), btnAudience.getY()-80);
        btnChangeQuestion.setLocation(btnChangeQuestion.getX(), btnChangeQuestion.getY()-80);
        lbl50_50.setVisible(true);
        btn50_50.setVisible(false);
    }//GEN-LAST:event_btn50_50MouseClicked

    private void btnAudienceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAudienceMouseClicked
        // TODO add your handling code here:
        resetLabel();
        btnPrevious.setVisible(true);
        btnChangeQuestion.setLocation(btnChangeQuestion.getX(), btnChangeQuestion.getY()-80);
        lblAudience.setVisible(true);
        btnAudience.setVisible(false);
    }//GEN-LAST:event_btnAudienceMouseClicked

    private void backHomeBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backHomeBTNMouseClicked
        // TODO add your handling code here:
        setVisible(false);
               
    }//GEN-LAST:event_backHomeBTNMouseClicked

    private void btnChangeQuestionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangeQuestionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChangeQuestionMouseEntered

    private void btnChangeQuestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangeQuestionMouseClicked
        // TODO add your handling code here:
        resetLabel();
        btnPrevious.setVisible(true);
        lblChangQuestion.setVisible(true);
        btnChangeQuestion.setVisible(false);
    }//GEN-LAST:event_btnChangeQuestionMouseClicked

    private void btnChatHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChatHelpMouseClicked
        // TODO add your handling code here:
        resetLabel();
        btnPrevious.setVisible(true);
        btn50_50.setLocation(btnChatHelp.getX(), btnChatHelp.getY()-50);
        btnAudience.setLocation(btnAudience.getX(), btnAudience.getY()-50);
        btnChangeQuestion.setLocation(btnChangeQuestion.getX(), btnChangeQuestion.getY()-40);
        lblChatHelp.setVisible(true);
        btnChatHelp.setVisible(false);
    }//GEN-LAST:event_btnChatHelpMouseClicked

    private void btnPreviousKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPreviousKeyPressed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_btnPreviousKeyPressed

    private void btnPreviousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPreviousMouseClicked
        // TODO add your handling code here:
        main_HowToPlay.setVisible(true);
        lbl50_50.setVisible(false);
        lblAudience.setVisible(false);
        lblChangQuestion.setVisible(false);
        lblChatHelp.setVisible(false);
        btnPrevious.setVisible(false);
    }//GEN-LAST:event_btnPreviousMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HowToPlay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backHomeBTN;
    private javax.swing.JLabel btn50_50;
    private javax.swing.JLabel btnAudience;
    private javax.swing.JLabel btnChangeQuestion;
    private javax.swing.JLabel btnChatHelp;
    private javax.swing.JLabel btnPrevious;
    private javax.swing.JLabel lbl50_50;
    private javax.swing.JLabel lblAudience;
    private javax.swing.JLabel lblChangQuestion;
    private javax.swing.JLabel lblChatHelp;
    private javax.swing.JLabel main_HowToPlay;
    // End of variables declaration//GEN-END:variables
}
