/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ailatrieuphu;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.JFrame;

/**
 *
 * @author mnngu
 */
public class khanGia extends javax.swing.JFrame {

    /**
     * Creates new form khanGia
     */
    private int width = 1200;
    private int height = 690;
    private BufferedImage image;
    static String correctAns;
    public khanGia() throws IOException {
        initComponents();
        setSize(width, height);
        
        setLocationRelativeTo(null);
        //setResizable(false);
        setTitle("Y Kien Khan Gia");
        setVisible(true);
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        lblKhanGiaA.setVisible(false);
        lblKhanGiaB.setVisible(false);
        lblKhanGiaC.setVisible(false);
        lblkhanGiaD.setVisible(false);
        
        switch (correctAns) {
            case "A":
                lblKhanGiaA.setVisible(true);
                break;
            case "B":
                lblKhanGiaB.setVisible(true);
                break;
            case "C":
                lblKhanGiaC.setVisible(true);
                break;
            case "D":
                lblkhanGiaD.setVisible(true);
                break;
            
        }
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblKhanGiaD = new javax.swing.JLabel();
        doneBTN = new javax.swing.JLabel();
        lblKhanGiaA = new javax.swing.JLabel();
        lblKhanGiaC = new javax.swing.JLabel();
        lblkhanGiaD = new javax.swing.JLabel();
        lblKhanGiaB = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        lblKhanGiaD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/khanGiaD.png"))); // NOI18N
        lblKhanGiaD.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        doneBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_X.png"))); // NOI18N
        doneBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        doneBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doneBTNMouseClicked(evt);
            }
        });
        getContentPane().add(doneBTN);
        doneBTN.setBounds(1030, 30, 90, 90);

        lblKhanGiaA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/khanGiaA.png"))); // NOI18N
        lblKhanGiaA.setText("jLabel4");
        getContentPane().add(lblKhanGiaA);
        lblKhanGiaA.setBounds(0, 0, 1200, 670);

        lblKhanGiaC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/khanGiaC.png"))); // NOI18N
        lblKhanGiaC.setText("jLabel1");
        getContentPane().add(lblKhanGiaC);
        lblKhanGiaC.setBounds(0, 0, 1200, 670);

        lblkhanGiaD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/khanGiaD.png"))); // NOI18N
        lblkhanGiaD.setText("jLabel1");
        getContentPane().add(lblkhanGiaD);
        lblkhanGiaD.setBounds(0, 0, 1200, 670);

        lblKhanGiaB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/khanGiaB.png"))); // NOI18N
        lblKhanGiaB.setText("jLabel1");
        getContentPane().add(lblKhanGiaB);
        lblKhanGiaB.setBounds(0, 0, 1200, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneBTNMouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_doneBTNMouseClicked

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(khanGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(khanGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(khanGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(khanGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new khanGia().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(khanGia.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel doneBTN;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblKhanGiaA;
    private javax.swing.JLabel lblKhanGiaB;
    private javax.swing.JLabel lblKhanGiaC;
    private javax.swing.JLabel lblKhanGiaD;
    private javax.swing.JLabel lblkhanGiaD;
    // End of variables declaration//GEN-END:variables
}
