/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ailatrieuphu;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

import javax.swing.JFrame;


/**
 *
 * @author mnngu
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form qLottery
     */
    private int width = 1200;
    private int height = 680;
    private Member mem;
    private Play p;
    HowToPlay h;
    Clip spinningClip;
    public Menu() {
        initComponents();
        setSize(width, height);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setTitle("Ai La Trieu Phu [Menu]");
        setResizable(false);
        setVisible(true);
        String fileName="Nhac-nen-game-show-ai-la-trieu-phu-www_tiengdong_com.wav";
        playCorrectSound();

    }
    private void playCorrectSound() {
        try {
            // Load the audio file from the resources folder
            InputStream inputStream = getClass().getResourceAsStream("/sound/game.wav");
            if (inputStream == null) {
                System.err.println("Resource not found: /music/correct.wav");
                return;
            }
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(inputStream);
            spinningClip = AudioSystem.getClip();
            spinningClip.open(audioInputStream);
            spinningClip.start();
            // spinningClip.loop(Clip.LOOP_CONTINUOUSLY); // Loop the sound until stopped
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
            e.printStackTrace();
        }
    }
    public void playMusic(String location){
        try{
            File musicPath=new File (location);
            if (musicPath.exists()){
                
                AudioInputStream audioStream = AudioSystem.getAudioInputStream(musicPath);
                Clip clip=AudioSystem.getClip();
                
                clip.open(audioStream);
                clip.start();
              
            }
            else{
                System.out.println("Can't find file");
            }
        }catch(Exception e){
            System.out.println("difjai");
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        start_Button = new javax.swing.JLabel();
        btnOurMember = new javax.swing.JLabel();
        quitBtn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(1293, 202, 100, 100);

        start_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/startButton.png"))); // NOI18N
        start_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        start_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                start_ButtonMouseClicked(evt);
            }
        });
        getContentPane().add(start_Button);
        start_Button.setBounds(490, 360, 200, 70);

        btnOurMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/outMemberButton.png"))); // NOI18N
        btnOurMember.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOurMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOurMemberMouseClicked(evt);
            }
        });
        getContentPane().add(btnOurMember);
        btnOurMember.setBounds(430, 430, 280, 70);

        quitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/quitBtn.png"))); // NOI18N
        quitBtn.setText("jLabel2");
        quitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitBtnMouseClicked(evt);
            }
        });
        getContentPane().add(quitBtn);
        quitBtn.setBounds(550, 570, 100, 70);

        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(520, 510, 160, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1200, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        this.getContentPane().setBackground(Color.black);
    }//GEN-LAST:event_formMouseMoved

    private void start_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_start_ButtonMouseClicked
        // TODO add your handling code here:
        p=new Play();
        spinningClip.stop();
    }//GEN-LAST:event_start_ButtonMouseClicked

    private void btnOurMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOurMemberMouseClicked
        // TODO add your handling code here:
        mem=new Member();
    }//GEN-LAST:event_btnOurMemberMouseClicked

    private void quitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitBtnMouseClicked
        // TODO add your handling code here:
        Quit q=new Quit();
    }//GEN-LAST:event_quitBtnMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        h=new HowToPlay();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnOurMember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel quitBtn;
    private javax.swing.JLabel start_Button;
    // End of variables declaration//GEN-END:variables
}
