/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ailatrieuphu;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author mnngu
 */
public class winning extends javax.swing.JFrame {

    /**
     * Creates new form winning
     */
    private int width = 1200;
    private int height = 690;
    static String reward="";
    static int typeOfReward;
    int sec;
    private Timer time;
    public winning() {
        initComponents();
        setSize(width, height);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setTitle("Ai La Trieu Phu [Winning]");
        setResizable(false);
        setVisible(true);
        lbl1.setVisible(false);
        lbl2.setVisible(false);
        lbl3.setVisible(false);
        lbl4.setVisible(false);
        lblNothing.setVisible(false);
        setLabel();
        sec=7;
        time = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (sec == 0) {
                    setVisible(false);
                           
                           
                }
                sec--;
                
            }

        });
        time.start();
    }
    public void setLabel(){
        switch (typeOfReward){
            case 0:
                lblNothing.setVisible(true);
                break;
            case 1:
                lbl1.setVisible(true);
                break;
            case 2:
                lbl2.setVisible(true);
                break;
            case 3:
                lbl3.setVisible(true);
                break;
            case 4:
                lbl4.setVisible(true);
                break;
        }
        txtReward.setText(reward);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtReward = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lblNothing = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txtReward.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        txtReward.setForeground(new java.awt.Color(255, 102, 102));
        getContentPane().add(txtReward);
        txtReward.setBounds(240, 370, 550, 100);

        lbl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/20.png"))); // NOI18N
        getContentPane().add(lbl4);
        lbl4.setBounds(0, 0, 1200, 670);

        lbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/19.png"))); // NOI18N
        lbl3.setText("jLabel1");
        getContentPane().add(lbl3);
        lbl3.setBounds(-40, 0, 1200, 670);

        lbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/18.png"))); // NOI18N
        getContentPane().add(lbl2);
        lbl2.setBounds(0, 0, 1200, 670);

        lbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/17.png"))); // NOI18N
        getContentPane().add(lbl1);
        lbl1.setBounds(0, 0, 1200, 670);

        lblNothing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/16.png"))); // NOI18N
        getContentPane().add(lblNothing);
        lblNothing.setBounds(0, 0, 1159, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(winning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(winning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(winning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(winning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new winning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lblNothing;
    private javax.swing.JLabel txtReward;
    // End of variables declaration//GEN-END:variables
}
